import type { Metadata } from "next";
import {Public_Sans, Geist, Geist_Mono} from "next/font/google";
import "@shopvendly/ui/globals.css";

const publicSans = Public_Sans({subsets:['latin'],variable:'--font-public-sans'});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} ${publicSans.variable}`}>
        {children}
      </body>
    </html>
  );
}
